language: elixir
otp_release:
  - 17.5
  - 18.0
elixir:
  - 1.0.5
before_script:
  - export SCRIVENER_DB_USER=postgres
  - mix local.hex --force
  - mix deps.get --only test
  - MIX_ENV=test mix scrivener.db.reset
